#!/usr/bin/env python3
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GLib
import subprocess, os

BRIGHTNESSCTL = "/usr/bin/brightnessctl"
SUDO = ["/usr/bin/sudo", "-n"]

def run_cmd(cmd):
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=5)
    except:
        return None

def get_brightness():
    r = run_cmd(SUDO + [BRIGHTNESSCTL, "-m"])
    if r and r.returncode == 0:
        parts = r.stdout.strip().split(",")
        if len(parts) >= 4:
            return int(parts[3].rstrip("%"))
    return None

def set_brightness(val):
    run_cmd(SUDO + [BRIGHTNESSCTL, "set", f"{val}%"])

class BrightnessApp(Gtk.Window):
    def __init__(self):
        super().__init__(title="Pop Brightness")
        self.set_border_width(20)
        self.set_default_size(400, 150)
        self.set_position(Gtk.WindowPosition.CENTER)
        self.set_resizable(False)
        self.connect("destroy", Gtk.main_quit)

        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=12)
        self.add(vbox)

        header = Gtk.HeaderBar()
        header.set_show_close_button(True)
        header.set_title("Pop Brightness")
        self.set_titlebar(header)

        self.label = Gtk.Label()
        self.label.set_markup("<b>Brightness: --%</b>")
        vbox.pack_start(self.label, False, False, 0)

        self.slider = Gtk.Scale.new_with_range(
            Gtk.Orientation.HORIZONTAL, 1, 100, 1)
        self.slider.set_value_pos(Gtk.PositionType.BOTTOM)
        self.slider.set_size_request(350, -1)
        self.slider.connect("value-changed", self.on_slider)
        vbox.pack_start(self.slider, False, False, 0)

        hbox = Gtk.Box(spacing=8)
        hbox.set_halign(Gtk.Align.CENTER)
        vbox.pack_start(hbox, False, False, 0)

        minus_btn = Gtk.Button(label="-1%")
        minus_btn.set_size_request(60, -1)
        minus_btn.connect("clicked", self.on_minus)
        hbox.pack_start(minus_btn, False, False, 0)

        plus_btn = Gtk.Button(label="+1%")
        plus_btn.set_size_request(60, -1)
        plus_btn.connect("clicked", self.on_plus)
        hbox.pack_start(plus_btn, False, False, 0)

        self.refresh()

    def refresh(self):
        val = get_brightness()
        if val is not None:
            self.label.set_markup(f"<b>Brightness: {val}%</b>")
            self.slider.handler_block_by_func(self.on_slider)
            self.slider.set_value(val)
            self.slider.handler_unblock_by_func(self.on_slider)

    def on_slider(self, slider):
        val = int(slider.get_value())
        set_brightness(val)
        self.label.set_markup(f"<b>Brightness: {val}%</b>")

    def on_minus(self, btn):
        val = get_brightness()
        if val is not None:
            new = max(1, val - 1)
            set_brightness(new)
            self.refresh()

    def on_plus(self, btn):
        val = get_brightness()
        if val is not None:
            new = min(100, val + 1)
            set_brightness(new)
            self.refresh()

if __name__ == "__main__":
    app = BrightnessApp()
    app.show_all()
    Gtk.main()
